name = "K256"
uuid = "d263101d-adff-4eab-ae50-a0254ef116d7"
version = "0.1.0"
authors = ["K256 <support@k256.xyz>"]

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
HTTP = "1"
JSON3 = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
